name: Deploy to Render

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Change this to your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} # Add your Render API key as a GitHub secret
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }} # Add your Render service ID as a GitHub secret
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"force": true}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
